version: '3.4'

services:
  memegame.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8090:8090"