version: '3.4'

networks:
  meme-network:
    driver: bridge 

services:
  memegame.api:
    image: darcy3812/memegameapi:latest
    build:
      context: .
      dockerfile: MemeGame.API/Dockerfile
    depends_on:
      - memegame.db
    networks:
      - meme-network 

  memegame.db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: "Meme"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - meme-network

volumes:
  db_volume: