version: '3.4'

services:
  memegame.front:
    image: darcy3812/memegamefront:latest
    build:
      context: meme-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./meme-front:/app
      - /app/node_modules
    command: npm run dev

  memegame.api:
    image: darcy3812/memegameapi:latest   
    build:
      context: .
      dockerfile: MemeGame.API/Dockerfile
    depends_on:
      - memegame.db 

  memegame.db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: "Meme"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  memegame.bot:
    image: darcy3812/memegamebot:latest
    environment:
      POSTGRES_DB: "Meme"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"