name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
defaults:
 run:
  working-directory: ./MemeGame
jobs:
  build:
    environment: dev 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MemeGame.sln
    - name: Build
      run: dotnet build ./MemeGame.sln --no-restore
    - name: Test
      run: dotnet test ./MemeGame.sln --no-build --verbosity n
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:         
          file: ./MemeGame.API/Dockerfile
          push: true
          tags: darcy3812/memegameapi:latest
    
